### ISSUE TITLE
Application Roles

### ISSUE THREAD

**Issue by Faculewis** [cognizant-softvision/donate-to#122]
The application will have 4 types of roles and these roles should be added to the seed of the database.

A - Superadmin: for the owner of the aplication.
 - Can perform CRUD operations of the donations requests from all organizations
- Can associate/disassociate users to organizations.
- Can perform CRUD operations of organizations
B - Admin: for the responsible of an organization.
 - Can perform CRUD operations of the donations requests from all organizations
- Can associate/disassociate users to organizations.
C- Organization: user associated to an organization.
 - Can perform CRUD operations of the donations requests from all organizations
D - Donor: user that will donate resources.
 - Can perform CRUD operations of the donations made by him

**Comment by nicolasgranata** [comment]
The first time that an user is registered, the role assigned is Donor, right? @Faculewis

**Comment by Faculewis** [comment]
> The first time that an user is registered, the role assigned is Donor, right? @Faculewis

Yes, that's right.

**Comment by nicolasgranata** [comment]
> > The first time that an user is registered, the role assigned is Donor, right? @Faculewis
> 
> Yes, that's right.

Great, I'm going to create an issue to track that flow down.
