### ISSUE TITLE
Server error appears with unauthorized message 

### ISSUE THREAD

**Issue by aupace** [cognizant-softvision/donate-to#187]
Sometimes there is a server error for unauthorized message when user tries to create a donation request or donate an item.

Important comments:

- Screenshot attached

![server error identity](https://user-images.githubusercontent.com/42481106/84510212-36f29f80-ac9b-11ea-94f0-bc2cbd73ed51.png)

STR:

1. Open website
2. Go to admin panel
3. Click to create a new donation request

1. Open website
2. Click on donate for any donation request

Obtained results: A server error with unauthorized message appears.

Expected results: No error should appear.

**Comment by aupace** [comment]
This issue is still reproducible.

![error unauthrized](https://user-images.githubusercontent.com/42481106/85136200-aaedf400-b215-11ea-912f-e225f3365d21.png)

**Comment by aupace** [comment]
This issue is still reproducible.

**Comment by matigrieben** [comment]
Apparently you are a user without the right privileges.
![image](https://user-images.githubusercontent.com/23266399/86051727-40666080-ba2c-11ea-946c-d8a116ea1934.png)
Maybe we shouldn't let the user enter the create page in the first place, right?

**Comment by matigrieben** [comment]
Could you try again with those privileges?

**Comment by aupace** [comment]
This issue is still reproducible using an user with "Admin" status/privileges.

Important comments:

- User was augusto.pace+admin@softvision.com 

![image](https://user-images.githubusercontent.com/42481106/86150122-53803b80-bad3-11ea-8790-f7009e3888a3.png)

**Comment by aupace** [comment]
Could this issue could be related to an automatic logoff from the system on the backend that user is not aware on frontend? @matigrieben

**Comment by aupace** [comment]
This issue is still reproducible:

![image](https://user-images.githubusercontent.com/42481106/86417749-64cc7200-bca4-11ea-8408-100052f396f2.png)

**Comment by aupace** [comment]
Fix verified.
