### ISSUE TITLE
Identity number and Phone number can be letters in Responsable view

### ISSUE THREAD

**Issue by aupace** [cognizant-softvision/donate-to#228]
When user is making a donation, on the Responsable page of the flow, the user is allowed to put letters or some special characters on the Identity number and Phone number.

Important comments:

- Screenshot attached:

![identity number](https://user-images.githubusercontent.com/42481106/85872575-5367ff00-b7a6-11ea-9436-476778969dab.png)
![phone umber](https://user-images.githubusercontent.com/42481106/85872577-54009580-b7a6-11ea-892f-c70c1f8925c4.png)

STR:

1. Open webiste
2. Go to any donation
3. Start the donation process
4. Reach the responsable page

Obtained results: User is allowed to put letters or special characters in Phone Number and Identity Number.

Expected results: User should only be able to put numbers and only some special characters.

**Comment by guillemurano** [comment]
I would change the Identity Number label to Identity ID or just ID but maintaining the alphanumeric value according to the different approaches used per country

**Comment by aupace** [comment]
Fix verified.
