### ISSUE TITLE
Unregistered user flow

### ISSUE THREAD

**Issue by Faculewis** [cognizant-softvision/donate-to#25]
As an unregistered user, I need to see all donation requests on the main page and be able to see the details of the requests.

Acceptance Criteria:

A - Navigate to home page
B - To be able to search for donation requests by institution, category or item
C- To be able to see the details of the donation request that I select
D - You should see an indicator that donation requests are being loaded and their details.
E - When you click on donate you must go to the registration page

**Comment by aupace** [comment]
Flow verified.
