### ISSUE TITLE
Registered user flow

### ISSUE THREAD

**Issue by Faculewis** [cognizant-softvision/donate-to#26]
As a user, I need to see all donation requests on the main page and be able to see the details of the requests.

Acceptance Criteria:
A - Navigate to home page
B - To be able to search for donation requests by institution, category or item
C - To be able to see the details of the donation request that I select
D - You should see an indicator that donation requests are being loaded and their details.
E - When you click on donate you must go to the donation page.
F - The Donation page should show all the information of the request
G - In the list or table of items, the user can specify which and how much to donate of each item.
H - Once the user click in the button, validate if is almost one item able to be donate.
I - If there are no items, an alert should be displayed. 
J - If there is almost one item, a popup (modal) must be displayed.
K- In the modal should be an stepper with 3 steps:
 1. Responsable: Here the user must fulfill the information of the person that is in charge of the donation.
2. Address: The location where the items should be picked up.
3. Finish: A summary of all the information of the donation and a button to confirm

**Comment by aupace** [comment]
Flow verified.
