### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by Faculewis** [cognizant-softvision/donate-to#5]
As a customer, I want to create login credentials so I can securely access my self-service online account

Acceptance Criteria:
A - Input data fields to enter -
1) First Name
2) Last Name
3) E-mail
2) Password
3) Re-enter Password

B- Password data field specifications - At least 8 characters, 1 number, 1 uppercase letter, 1 lowercase letter

C - All fields are required data fields - error alert should be shown if the user clicks on Submit with any of the fields left blank

D - User should be prompted if email entered already exists in the system - error message
"Email registered - please enter another email or sign in"

E - Password criteria should be displayed to the user when the user clicks inside the password data field.

F - Green check mark, or something similar, next to 'Password' data field should be displayed that indicates to the user after typing password that the entry meets criteria

G - Red cross mark, or something similar, next to 'Password' data field should be displayed that indicates to the user after typing password that the entry does not meet criteria

H - Validate that inputs in 'Password' and 'Re-enter Password' data fields match-
Green check mark, or something similar, next to 'Re-enter' password data field should be displayed that indicates to the user after typing if passwords match

I - If 'Password' entry does not match criteria specified and user hits Submit, show error alert "Password entry does not meet criteria"

J - If entries in 'Password' and 'Re-enter Password' do not match and user hits Submit, show error alert 'Password entries do not match'

K - After successful validation of all entered fields and on clicking Submit, show message indicating successful online account creation

L - Route user to Splash screen (Login screen)

**Comment by nicolasgranata** [comment]
@Lordapa we have an endpoint in the identity server for registering users

**Comment by aupace** [comment]
Flow verified.
