### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Faculewis** [cognizant-softvision/donate-to#6]
As a customer, I want to login so I can securely access my self-service online account

Acceptance Criteria:
A - Input data fields to enter -
1) E-mail
2) Password

B - All fields are required data fields - error alert should be shown if the user clicks on Submit with any of the fields left blank

C - If the user was not found in the database, show error alert “Incorrect user or password”

D - If 'Password' entry does not match, show error alert “Incorrect user or password”

E - After successful validation of the user credentials route user to Admin page if it is an organization’s user or home page if it is a donator user

**Comment by aupace** [comment]
Flow verified.
