### ISSUE TITLE
Search and associate user

### ISSUE THREAD

**Issue by Faculewis** [cognizant-softvision/donate-to#77]
As a user with admin permissions, I should be able to search for other already registered user and associate it with one of my organizations.

A- The user has to be an administrator to be able to search for other user.
B- The admin user can only associate users to any of its organizations
C- Once the user is associated with any organization, their permissions must be administrator of those organizations

This Issue has the following children/dependencies to e completed in order:

1. - [x] #168 Handle Role and Claims Per Organization

2. - [x] #176 Create API Resource To Link A User To An Organization 

3. - [x]   #192 Create View To Asociate A User

4. - [x]  #195 Create Restriccions to Update, retrieval and creation of Donation Requests And Users Related To A Specific Organization Based On Role And Claim Rules

**Comment by aupace** [comment]
This feature is working and verified.
